"""Generated by tools/gen.py from sheets/*.json. Do not edit; change the sheet."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EffectsRow:
    """What a Skyrim skill does on Pandora. Magnitude = per_level x (skill - start) + per_perk x perks taken in that tree, capped (columns on the skills sheet)."""

    id: str
    kind: str
    hook: str
    applies_to: str
    damage_types: str
    pandora_text: str


EFFECTS: dict[str, EffectsRow] = {
    'e_one_handed': EffectsRow(id='e_one_handed', kind='damage_out', hook='h_enemy_damage', applies_to='pistol, SMG and melee damage', damage_types='WillowDmgSource_Pistol,WillowDmgSource_SubMachineGun,WillowDmgSource_Melee,WillowDmgSource_MeleeWithBlade', pandora_text='+{v}% pistol, SMG and melee damage'),
    'e_two_handed': EffectsRow(id='e_two_handed', kind='damage_out', hook='h_enemy_damage', applies_to='shotgun and rocket launcher damage', damage_types='WillowDmgSource_Shotgun,WillowDmgSource_Rocket', pandora_text='+{v}% shotgun and launcher damage'),
    'e_archery': EffectsRow(id='e_archery', kind='damage_out', hook='h_enemy_damage', applies_to='sniper and assault rifle damage', damage_types='WillowDmgSource_Sniper,WillowDmgSource_MachineGun', pandora_text='+{v}% sniper and assault rifle damage'),
    'e_block': EffectsRow(id='e_block', kind='damage_in', hook='h_player_damage', applies_to='damage taken while the shield is up', damage_types='-', pandora_text='-{v}% damage taken while your shield holds'),
    'e_smithing': EffectsRow(id='e_smithing', kind='damage_out', hook='h_enemy_damage', applies_to='all gun damage (well-kept gear)', damage_types='WillowDmgSource_Pistol,WillowDmgSource_SubMachineGun,WillowDmgSource_Shotgun,WillowDmgSource_Rocket,WillowDmgSource_Sniper,WillowDmgSource_MachineGun,WillowDmgSource_Bullet', pandora_text='+{v}% damage with every gun'),
    'e_heavy_armor': EffectsRow(id='e_heavy_armor', kind='damage_in', hook='h_player_damage', applies_to='damage taken to health', damage_types='-', pandora_text='-{v}% damage taken to health'),
    'e_light_armor': EffectsRow(id='e_light_armor', kind='move_speed', hook='h_tick', applies_to='ground speed', damage_types='-', pandora_text='+{v}% movement speed'),
    'e_pickpocket': EffectsRow(id='e_pickpocket', kind='money_bonus', hook='h_tick', applies_to='cash picked up', damage_types='-', pandora_text='+{v}% cash from pickups'),
    'e_lockpicking': EffectsRow(id='e_lockpicking', kind='chest_money', hook='h_use_object', applies_to='opening a chest also finds cash', damage_types='-', pandora_text="Chests hold {v}% of a level's worth of extra cash"),
    'e_sneak': EffectsRow(id='e_sneak', kind='crit_bonus', hook='h_enemy_damage', applies_to='critical hits', damage_types='-', pandora_text='+{v}% critical hit damage'),
    'e_alchemy': EffectsRow(id='e_alchemy', kind='damage_out', hook='h_enemy_damage', applies_to='burn, corrode, shock and slag damage over time', damage_types='WillowDmgSource_StatusEffect', pandora_text='+{v}% elemental damage over time'),
    'e_speech': EffectsRow(id='e_speech', kind='money_refund', hook='h_vendor_buy_post', applies_to='vending machine prices (refund on buy, bonus on sell)', damage_types='-', pandora_text='{v}% better prices at vending machines'),
    'e_alteration': EffectsRow(id='e_alteration', kind='regen_shield', hook='h_tick', applies_to='shield recharge once it has started', damage_types='-', pandora_text='Shield recharges {v}% of capacity per second faster'),
    'e_conjuration': EffectsRow(id='e_conjuration', kind='damage_out', hook='h_enemy_damage', applies_to='grenade damage', damage_types='WillowDmgSource_Grenade', pandora_text='+{v}% grenade damage'),
    'e_destruction': EffectsRow(id='e_destruction', kind='damage_out', hook='h_enemy_damage', applies_to='direct hits from elemental guns', damage_types='WillowDmgSource_Pistol,WillowDmgSource_SubMachineGun,WillowDmgSource_Shotgun,WillowDmgSource_Rocket,WillowDmgSource_Sniper,WillowDmgSource_MachineGun', pandora_text='+{v}% damage with elemental guns'),
    'e_illusion': EffectsRow(id='e_illusion', kind='damage_out', hook='h_enemy_damage', applies_to='all damage while in Fight For Your Life', damage_types='*', pandora_text='+{v}% damage while Fighting For Your Life'),
    'e_restoration': EffectsRow(id='e_restoration', kind='regen_health', hook='h_tick', applies_to='health regeneration', damage_types='-', pandora_text='Regenerate {v}% of max health per second'),
    'e_enchanting': EffectsRow(id='e_enchanting', kind='status_chance', hook='h_tick', applies_to="held gun's elemental effect chance", damage_types='-', pandora_text='+{v}% elemental effect chance'),
}

@dataclass(frozen=True)
class FeaturesRow:
    """What version 0.1 promises a player. Every row must be in the build and, before listing, seen in the real game."""

    id: str
    feature: str
    version: str
    sheets: str


FEATURES: dict[str, FeaturesRow] = {
    'ft_opening': FeaturesRow(id='ft_opening', feature="New game opens with Skyrim's 'you're finally awake' greeting and a race choice", version='0.1', sheets='ui,skyrim_reads'),
    'ft_skills': FeaturesRow(id='ft_skills', feature='All 18 Skyrim skills level up from Borderlands play', version='0.1', sheets='skills,xp_sources,formulas'),
    'ft_effects': FeaturesRow(id='ft_effects', feature="Each skill's level and perks change Borderlands stats", version='0.1', sheets='skills,effects'),
    'ft_perks': FeaturesRow(id='ft_perks', feature="Skyrim's real perk trees, read from the player's Skyrim, spent with Dragonborn level-ups", version='0.1', sheets='skyrim_reads,ui'),
    'ft_class_off': FeaturesRow(id='ft_class_off', feature='Class skill trees and class action skill replaced', version='0.1', sheets='hooks,ui'),
    'ft_shout': FeaturesRow(id='ft_shout', feature='Unrelenting Force on the action-skill key, words unlocking with level', version='0.1', sheets='shout,keybinds,sounds'),
    'ft_save': FeaturesRow(id='ft_save', feature='Progress saved per Borderlands character', version='0.1', sheets='hooks'),
    'ft_voice': FeaturesRow(id='ft_voice', feature="Skyrim's real FUS RO DAH voice and UI sounds", version='later', sheets='sounds'),
    'ft_coop': FeaturesRow(id='ft_coop', feature='Co-op', version='later', sheets='-'),
}

@dataclass(frozen=True)
class FormulasRow:
    """Numbers behind Skyrim's progression, read from the player's Skyrim.esm (GMST records). fallback is only used when a value is absent from the file, and is logged."""

    id: str
    source: str
    type: str
    fallback: float
    used_for: str


FORMULAS: dict[str, FormulasRow] = {
    'f_level_base': FormulasRow(id='f_level_base', source='GMST:fXPLevelUpBase', type='float', fallback=75.0, used_for='character XP for the next level = base + mult x level'),
    'f_level_mult': FormulasRow(id='f_level_mult', source='GMST:fXPLevelUpMult', type='float', fallback=25.0, used_for='see f_level_base'),
    'f_xp_per_rank': FormulasRow(id='f_xp_per_rank', source='GMST:fXPPerSkillRank', type='float', fallback=1.0, used_for='character XP per skill increase = this x new skill level'),
    'f_skill_curve': FormulasRow(id='f_skill_curve', source='GMST:fSkillUseCurve', type='float', fallback=1.95, used_for='skill XP to next level = improve_mult x level^curve + improve_offset'),
    'f_skill_start': FormulasRow(id='f_skill_start', source='GMST:iAVDSkillStart', type='int', fallback=15.0, used_for="every skill's starting level before race bonuses"),
    'f_skill_max': FormulasRow(id='f_skill_max', source='fixed', type='int', fallback=100.0, used_for="skill level cap (Skyrim's 100, no Legendary in 0.1)"),
    'f_perks_per_level': FormulasRow(id='f_perks_per_level', source='fixed', type='int', fallback=1.0, used_for='perk points gained per character level'),
    'f_use_mult': FormulasRow(id='f_use_mult', source='AVIF.AVSK[0]', type='float', fallback=1.0, used_for='skill XP per use = use_mult x base_xp + use_offset'),
    'f_use_offset': FormulasRow(id='f_use_offset', source='AVIF.AVSK[1]', type='float', fallback=0.0, used_for='see f_use_mult'),
    'f_improve_mult': FormulasRow(id='f_improve_mult', source='AVIF.AVSK[2]', type='float', fallback=1.0, used_for='see f_skill_curve'),
    'f_improve_offset': FormulasRow(id='f_improve_offset', source='AVIF.AVSK[3]', type='float', fallback=0.0, used_for='see f_skill_curve'),
}

@dataclass(frozen=True)
class HooksRow:
    """Every Borderlands 2 function the mashup hooks. Names checked against the OpenBLCMM BL2 object data (in_data); in_game is only 'yes' after a run in the real game."""

    id: str
    function: str
    type: str
    args_used: str
    purpose: str


HOOKS: dict[str, HooksRow] = {
    'h_action_skill': HooksRow(id='h_action_skill', function='WillowGame.WillowPlayerController:StartActionSkill', type='pre', args_used='none', purpose='Block the class action skill; the shout replaces it'),
    'h_upgrade_skill': HooksRow(id='h_upgrade_skill', function='WillowGame.WillowPlayerController:ServerUpgradeSkill', type='pre', args_used='Skill', purpose='Block spending class skill points (class trees are replaced)'),
    'h_skills_menu': HooksRow(id='h_skills_menu', function='WillowGame.WillowPlayerController:ShowStatusMenu_Skills', type='pre', args_used='none', purpose='Open the Skyrim skills menu instead of the class skill tree'),
    'h_tick': HooksRow(id='h_tick', function='WillowGame.WillowPlayerController:PlayerTick', type='post', args_used='DeltaTime', purpose='Per-frame clock: regen, movement, currency and shield polling, cooldowns'),
    'h_enemy_damage': HooksRow(id='h_enemy_damage', function='WillowGame.WillowAIPawn:TakeDamage', type='pre', args_used='Damage, DamageType, InstigatedBy', purpose='The one damage-out hook: multiply damage by skill effects, award weapon/stealth/magic skill XP'),
    'h_player_damage': HooksRow(id='h_player_damage', function='WillowGame.WillowPlayerPawn:TakeDamage', type='pre', args_used='Damage', purpose='The one damage-in hook: Block / Heavy Armor reduction and XP'),
    'h_vendor_buy': HooksRow(id='h_vendor_buy', function='WillowGame.WillowVendingMachineBase:PlayerBuyItem', type='pre', args_used='WPC', purpose='Speech: note money before a purchase'),
    'h_vendor_buy_post': HooksRow(id='h_vendor_buy_post', function='WillowGame.WillowVendingMachineBase:PlayerBuyItem', type='post', args_used='WPC', purpose='Speech: refund part of the price, award XP'),
    'h_vendor_sell': HooksRow(id='h_vendor_sell', function='WillowGame.WillowVendingMachineBase:PlayerSellItem', type='pre', args_used='WPC', purpose='Speech: note money before a sale'),
    'h_vendor_sell_post': HooksRow(id='h_vendor_sell_post', function='WillowGame.WillowVendingMachineBase:PlayerSellItem', type='post', args_used='WPC', purpose='Speech: bonus on the sale, award XP'),
    'h_heal': HooksRow(id='h_heal', function='WillowGame.WillowPawn:HealDamage', type='pre', args_used='Amount, bIsShieldRestore', purpose='Restoration XP when the player is healed'),
    'h_add_inventory': HooksRow(id='h_add_inventory', function='WillowGame.WillowInventoryManager:AddInventory', type='post', args_used='NewItem', purpose='Smithing / Enchanting XP on picking up gear'),
    'h_use_object': HooksRow(id='h_use_object', function='WillowGame.WillowInteractiveObject:UsedBy', type='post', args_used='User', purpose='Lockpicking: opening chests and lockers'),
    'h_new_game': HooksRow(id='h_new_game', function='WillowGame.WillowPlayerController:ClientNotifyNewGameStarted', type='post', args_used='none', purpose="Mark a brand-new character for the 'finally awake' opening"),
    'h_possess': HooksRow(id='h_possess', function='WillowGame.WillowPlayerController:Possess', type='post', args_used='none', purpose='Player spawned or map loaded: reset per-map state, run the opening when due'),
}

@dataclass(frozen=True)
class KeybindsRow:
    """Keys the mashup adds (rebindable in the SDK's mod menu)."""

    id: str
    default_key: str
    action: str


KEYBINDS: dict[str, KeybindsRow] = {
    'k_shout': KeybindsRow(id='k_shout', default_key='F', action="Shout Unrelenting Force (Borderlands 2's action-skill key; the class action skill is blocked)"),
    'k_menu': KeybindsRow(id='k_menu', default_key='K', action='Open the Skyrim skills and perks menu'),
}

@dataclass(frozen=True)
class ShoutRow:
    """Unrelenting Force as the action skill, one row per word. Word names and cooldowns come from the player's Skyrim.esm (SHOU/WOOP); force and reach are this mashup's."""

    id: str
    words: int
    woop_edid: str
    unlock_level: int
    cooldown_source: str
    range_uu: int
    cone_deg: int
    push_speed: int
    lift_speed: int
    damage_frac: float
    camera_anim: str


SHOUT: dict[str, ShoutRow] = {
    'w_fus': ShoutRow(id='w_fus', words=1, woop_edid='WordFus', unlock_level=1, cooldown_source='SHOU.SNAM[0].recharge', range_uu=900, cone_deg=35, push_speed=900, lift_speed=250, damage_frac=0.05, camera_anim='Anim_CameraAnimations.Explosions.Canim_Explosion_Minor'),
    'w_ro': ShoutRow(id='w_ro', words=2, woop_edid='WordRo', unlock_level=5, cooldown_source='SHOU.SNAM[1].recharge', range_uu=1300, cone_deg=40, push_speed=1600, lift_speed=400, damage_frac=0.1, camera_anim='Anim_CameraAnimations.Explosions.Canim_Explosion_Medium'),
    'w_dah': ShoutRow(id='w_dah', words=3, woop_edid='WordDah', unlock_level=10, cooldown_source='SHOU.SNAM[2].recharge', range_uu=1800, cone_deg=45, push_speed=2600, lift_speed=650, damage_frac=0.2, camera_anim='Anim_CameraAnimations.Explosions.Canim_Explosion_WarriorEarthquake'),
}

@dataclass(frozen=True)
class SkillsRow:
    """Skyrim's 18 skills on Pandora. Names, descriptions, perk trees and XP multipliers are read from the player's Skyrim.esm (AVIF record found by editor id); this sheet only says how each one plays in Borderlands 2."""

    id: str
    avif_edid: str
    av_index: int
    school: str
    xp_source: str
    effect: str
    per_level: float
    per_perk: float
    cap: float


SKILLS: dict[str, SkillsRow] = {
    'one_handed': SkillsRow(id='one_handed', avif_edid='AVOneHanded', av_index=6, school='combat', xp_source='x_one_handed', effect='e_one_handed', per_level=0.4, per_perk=4.0, cap=100.0),
    'two_handed': SkillsRow(id='two_handed', avif_edid='AVTwoHanded', av_index=7, school='combat', xp_source='x_two_handed', effect='e_two_handed', per_level=0.4, per_perk=4.0, cap=100.0),
    'archery': SkillsRow(id='archery', avif_edid='AVMarksman', av_index=8, school='combat', xp_source='x_archery', effect='e_archery', per_level=0.4, per_perk=4.0, cap=100.0),
    'block': SkillsRow(id='block', avif_edid='AVBlock', av_index=9, school='combat', xp_source='x_block', effect='e_block', per_level=0.2, per_perk=2.0, cap=45.0),
    'smithing': SkillsRow(id='smithing', avif_edid='AVSmithing', av_index=10, school='combat', xp_source='x_smithing', effect='e_smithing', per_level=0.15, per_perk=1.5, cap=30.0),
    'heavy_armor': SkillsRow(id='heavy_armor', avif_edid='AVHeavyArmor', av_index=11, school='combat', xp_source='x_heavy_armor', effect='e_heavy_armor', per_level=0.2, per_perk=2.0, cap=45.0),
    'light_armor': SkillsRow(id='light_armor', avif_edid='AVLightArmor', av_index=12, school='stealth', xp_source='x_light_armor', effect='e_light_armor', per_level=0.1, per_perk=1.0, cap=25.0),
    'pickpocket': SkillsRow(id='pickpocket', avif_edid='AVPickpocket', av_index=13, school='stealth', xp_source='x_pickpocket', effect='e_pickpocket', per_level=0.5, per_perk=5.0, cap=100.0),
    'lockpicking': SkillsRow(id='lockpicking', avif_edid='AVLockpicking', av_index=14, school='stealth', xp_source='x_lockpicking', effect='e_lockpicking', per_level=0.1, per_perk=1.0, cap=20.0),
    'sneak': SkillsRow(id='sneak', avif_edid='AVSneak', av_index=15, school='stealth', xp_source='x_sneak', effect='e_sneak', per_level=0.5, per_perk=5.0, cap=150.0),
    'alchemy': SkillsRow(id='alchemy', avif_edid='AVAlchemy', av_index=16, school='stealth', xp_source='x_alchemy', effect='e_alchemy', per_level=0.5, per_perk=5.0, cap=120.0),
    'speech': SkillsRow(id='speech', avif_edid='AVSpeechcraft', av_index=17, school='stealth', xp_source='x_speech', effect='e_speech', per_level=0.15, per_perk=2.0, cap=30.0),
    'alteration': SkillsRow(id='alteration', avif_edid='AVAlteration', av_index=18, school='magic', xp_source='x_alteration', effect='e_alteration', per_level=0.03, per_perk=0.3, cap=6.0),
    'conjuration': SkillsRow(id='conjuration', avif_edid='AVConjuration', av_index=19, school='magic', xp_source='x_conjuration', effect='e_conjuration', per_level=0.5, per_perk=5.0, cap=120.0),
    'destruction': SkillsRow(id='destruction', avif_edid='AVDestruction', av_index=20, school='magic', xp_source='x_destruction', effect='e_destruction', per_level=0.4, per_perk=4.0, cap=100.0),
    'illusion': SkillsRow(id='illusion', avif_edid='AVMysticism', av_index=21, school='magic', xp_source='x_illusion', effect='e_illusion', per_level=1.0, per_perk=8.0, cap=200.0),
    'restoration': SkillsRow(id='restoration', avif_edid='AVRestoration', av_index=22, school='magic', xp_source='x_restoration', effect='e_restoration', per_level=0.01, per_perk=0.1, cap=2.5),
    'enchanting': SkillsRow(id='enchanting', avif_edid='AVEnchanting', av_index=23, school='magic', xp_source='x_enchanting', effect='e_enchanting', per_level=0.4, per_perk=4.0, cap=80.0),
}

@dataclass(frozen=True)
class SkyrimReadsRow:
    """Everything read from the player's own Skyrim Special Edition install at launch. Nothing from Skyrim is shipped with the mashup."""

    id: str
    file: str
    record: str
    fields: str
    used_for: str


SKYRIM_READS: dict[str, SkyrimReadsRow] = {
    'r_header': SkyrimReadsRow(id='r_header', file='Data/Skyrim.esm', record='TES4', fields='flags (localized 0x80)', used_for='whether names are string ids into the .strings tables'),
    'r_skills': SkyrimReadsRow(id='r_skills', file='Data/Skyrim.esm', record='AVIF', fields='EDID, FULL, DESC, AVSK, perk tree nodes (PNAM, FNAM, XNAM, YNAM, HNAM, VNAM, SNAM, CNAM, INAM)', used_for='the 18 skills: names, descriptions, XP multipliers, perk constellations'),
    'r_perks': SkyrimReadsRow(id='r_perks', file='Data/Skyrim.esm', record='PERK', fields='EDID, FULL, DESC, CTDA (GetBaseActorValue >= n), NNAM (next rank), DATA playable', used_for='perk names, descriptions, ranks and skill requirements'),
    'r_races': SkyrimReadsRow(id='r_races', file='Data/Skyrim.esm', record='RACE', fields='EDID, FULL, DESC, DATA (7 skill boosts, playable flag)', used_for='the race choice and starting skills'),
    'r_shout': SkyrimReadsRow(id='r_shout', file='Data/Skyrim.esm', record='SHOU', fields='EDID, FULL, DESC, SNAM (word, spell, recharge) x3', used_for='Unrelenting Force: its name, words and cooldowns'),
    'r_words': SkyrimReadsRow(id='r_words', file='Data/Skyrim.esm', record='WOOP', fields='EDID, FULL, TNAM', used_for='Fus / Ro / Dah and their translations'),
    'r_settings': SkyrimReadsRow(id='r_settings', file='Data/Skyrim.esm', record='GMST', fields='EDID, DATA', used_for='level-up and skill-curve numbers (formulas sheet)'),
    'r_strings': SkyrimReadsRow(id='r_strings', file='Data/Skyrim - Interface.bsa (or loose Data/Strings)', record='strings/skyrim_<language>.strings, .dlstrings', fields='string id -> text', used_for="all names and descriptions in the player's language"),
    'r_bsa': SkyrimReadsRow(id='r_bsa', file='Data/Skyrim - Interface.bsa', record='BSA v105 folder/file tables, LZ4 frame compression', fields='file data', used_for='getting the .strings files out of the archive'),
    'r_greeting': SkyrimReadsRow(id='r_greeting', file='Data/Strings ilstrings', record="string starting 'Hey, you. You're finally awake'", fields='text', used_for="Ralof's real opening line in the player's language (falls back to the mod's own quote)"),
}

@dataclass(frozen=True)
class SoundsRow:
    """Sounds played. BL2 sounds are Wwise events already in the game; Skyrim sounds would come from the player's Skyrim archives (stretch, not in 0.1)."""

    id: str
    source: str
    object: str
    played_on: str
    version: str


SOUNDS: dict[str, SoundsRow] = {
    's_level_up': SoundsRow(id='s_level_up', source='bl2', object='Ake_UI.UI_HUD.Ak_Play_UI_Alert_Level_Up', played_on='u_level_up', version='0.1'),
    's_shout': SoundsRow(id='s_shout', source='bl2', object='Ake_Mon_Goliath.Ak_Play_Mon_Goliath_AOE_Slam', played_on='w_fus', version='0.1'),
    's_fus_ro_dah_voice': SoundsRow(id='s_fus_ro_dah_voice', source='skyrim', object='Skyrim - Voices_en0.bsa: sound/voice/... (xWMA in .fuz; needs a decoder)', played_on='w_dah', version='later'),
}

@dataclass(frozen=True)
class TuningRow:
    """Every other number and pattern the in-game code uses, so nothing is hidden in code."""

    id: str
    value: float | str
    unit: str
    used_by: str


TUNING: dict[str, TuningRow] = {
    't_enemy_near_uu': TuningRow(id='t_enemy_near_uu', value=1500.0, unit='Unreal units (about 30 m)', used_by='x_light_armor'),
    't_moving_speed_uu': TuningRow(id='t_moving_speed_uu', value=200.0, unit='uu/s; slower counts as standing', used_by='x_light_armor'),
    't_scan_interval_s': TuningRow(id='t_scan_interval_s', value=1.0, unit='seconds between enemy scans', used_by='x_light_armor'),
    't_pawn_walk_limit': TuningRow(id='t_pawn_walk_limit', value=1000.0, unit='max pawns walked per scan (freeze guard)', used_by='w_fus'),
    't_shout_damage_cap': TuningRow(id='t_shout_damage_cap', value=3.0, unit="x the player's max health (keeps bosses sane)", used_by='w_fus'),
    't_chest_cash_base': TuningRow(id='t_chest_cash_base', value=25.0, unit='dollars at player level 1', used_by='e_lockpicking'),
    't_chest_cash_growth': TuningRow(id='t_chest_cash_growth', value=1.13, unit='x per player level', used_by='e_lockpicking'),
    't_chest_patterns': TuningRow(id='t_chest_patterns', value='_Treasure.,Lootables.', unit='InteractiveObjectDefinition path contains one of these', used_by='x_lockpicking'),
    't_rarity_xp_step': TuningRow(id='t_rarity_xp_step', value=0.5, unit='extra Smithing use per rarity level above white', used_by='x_smithing'),
    't_heal_min_frac': TuningRow(id='t_heal_min_frac', value=0.01, unit='heals smaller than this share of max health give no XP', used_by='x_restoration'),
    't_message_gap_s': TuningRow(id='t_message_gap_s', value=1.6, unit='seconds between HUD notices', used_by='h_tick'),
    't_opening_delay_s': TuningRow(id='t_opening_delay_s', value=2.0, unit='seconds after spawning before the greeting', used_by='h_possess'),
}

@dataclass(frozen=True)
class UiRow:
    """Every screen and message the mashup shows, built from Borderlands 2's own dialog boxes and HUD messages (ui_utils), filled with Skyrim's text."""

    id: str
    widget: str
    opened_by: str
    title: str
    body: str


UI: dict[str, UiRow] = {
    'u_greeting': UiRow(id='u_greeting', widget='TrainingBox', opened_by='h_possess', title='{greeting}', body="Ralof's opening line from the player's Skyrim strings, then 'Choose who you are.'"),
    'u_race': UiRow(id='u_race', widget='OptionBox', opened_by='u_greeting', title='Choose your race', body='one button per playable Skyrim race; tip = race description + skill bonuses'),
    'u_skills': UiRow(id='u_skills', widget='OptionBox', opened_by='k_menu', title='{race} - Level {level} - Perk points: {points}', body='18 skill buttons grouped combat/stealth/magic; tip = Skyrim description, XP bar, Pandora effect'),
    'u_skills_tab': UiRow(id='u_skills_tab', widget='OptionBox', opened_by='h_skills_menu', title='same as u_skills', body='the class skill tab opens the Skyrim skills menu'),
    'u_perks': UiRow(id='u_perks', widget='OptionBox', opened_by='u_skills', title='{skill} {level} - Perk points: {points}', body='one button per perk node, constellation order; tip = Skyrim perk text, rank, requirement, Pandora effect'),
    'u_skill_up': UiRow(id='u_skill_up', widget='hud_message', opened_by='h_tick', title='{skill} increased to {level}', body="Skyrim's skill-up notice"),
    'u_level_up': UiRow(id='u_level_up', widget='hud_message', opened_by='h_tick', title='You have reached level {level}', body="plus 'Perk point available' (open with the skills key)"),
    'u_word_learned': UiRow(id='u_word_learned', widget='hud_message', opened_by='h_tick', title='Word of Power learned: {word}', body='the word and its translation from Skyrim'),
    'u_shout_ready': UiRow(id='u_shout_ready', widget='hud_message', opened_by='h_tick', title='{shout}', body="'ready' when the cooldown ends; remaining seconds when pressed too early"),
    'u_class_sealed': UiRow(id='u_class_sealed', widget='hud_message', opened_by='h_upgrade_skill', title='Class skills are sealed', body='points into class trees are refused; points into Skyrim perks come from Dragonborn levels'),
    'u_no_skyrim': UiRow(id='u_no_skyrim', widget='TrainingBox', opened_by='h_possess', title='Skyrim not found', body='explains that the mashup reads Skyrim SE from the folder Melty passes, and that Skyrim features are off until it is found'),
}

@dataclass(frozen=True)
class XpSourcesRow:
    """What a player does in Borderlands 2 that counts as using a Skyrim skill. XP per event = Skyrim's own AVSK use multiplier x base_xp + AVSK use offset (read from the player's Skyrim.esm)."""

    id: str
    hook: str
    filter: str
    damage_types: str
    base_xp: float


XP_SOURCES: dict[str, XpSourcesRow] = {
    'x_one_handed': XpSourcesRow(id='x_one_handed', hook='h_enemy_damage', filter='player hits an enemy with a pistol, SMG or melee', damage_types='WillowDmgSource_Pistol,WillowDmgSource_SubMachineGun,WillowDmgSource_Melee,WillowDmgSource_MeleeWithBlade', base_xp=1.0),
    'x_two_handed': XpSourcesRow(id='x_two_handed', hook='h_enemy_damage', filter='player hits an enemy with a shotgun or rocket launcher', damage_types='WillowDmgSource_Shotgun,WillowDmgSource_Rocket', base_xp=1.5),
    'x_archery': XpSourcesRow(id='x_archery', hook='h_enemy_damage', filter='player hits an enemy with a sniper or assault rifle', damage_types='WillowDmgSource_Sniper,WillowDmgSource_MachineGun', base_xp=1.0),
    'x_block': XpSourcesRow(id='x_block', hook='h_player_damage', filter='player takes a hit while the shield is up', damage_types='-', base_xp=1.0),
    'x_smithing': XpSourcesRow(id='x_smithing', hook='h_add_inventory', filter='player picks up a gun or item; scaled by rarity level', damage_types='-', base_xp=1.0),
    'x_heavy_armor': XpSourcesRow(id='x_heavy_armor', hook='h_player_damage', filter='player takes a hit to health (shield down)', damage_types='-', base_xp=1.5),
    'x_light_armor': XpSourcesRow(id='x_light_armor', hook='h_tick', filter='each second moving at speed with a hostile within 30 m', damage_types='-', base_xp=0.5),
    'x_pickpocket': XpSourcesRow(id='x_pickpocket', hook='h_tick', filter='money goes up outside a vendor trade (cash pickups)', damage_types='-', base_xp=1.0),
    'x_lockpicking': XpSourcesRow(id='x_lockpicking', hook='h_use_object', filter='player opens a chest, locker, safe or box', damage_types='-', base_xp=4.0),
    'x_sneak': XpSourcesRow(id='x_sneak', hook='h_enemy_damage', filter='player lands a critical hit', damage_types='-', base_xp=1.5),
    'x_alchemy': XpSourcesRow(id='x_alchemy', hook='h_enemy_damage', filter="player's burn/corrode/shock/slag ticks hurt an enemy", damage_types='WillowDmgSource_StatusEffect', base_xp=0.5),
    'x_speech': XpSourcesRow(id='x_speech', hook='h_vendor_buy_post', filter='player buys or sells at a vending machine', damage_types='-', base_xp=3.0),
    'x_alteration': XpSourcesRow(id='x_alteration', hook='h_tick', filter='shield refills to full after being hit', damage_types='-', base_xp=2.0),
    'x_conjuration': XpSourcesRow(id='x_conjuration', hook='h_enemy_damage', filter="player's grenade hurts an enemy", damage_types='WillowDmgSource_Grenade', base_xp=2.0),
    'x_destruction': XpSourcesRow(id='x_destruction', hook='h_enemy_damage', filter='player hits an enemy with an elemental gun (direct hit)', damage_types='WillowDmgSource_Pistol,WillowDmgSource_SubMachineGun,WillowDmgSource_Shotgun,WillowDmgSource_Rocket,WillowDmgSource_Sniper,WillowDmgSource_MachineGun', base_xp=1.0),
    'x_illusion': XpSourcesRow(id='x_illusion', hook='h_tick', filter='player falls into Fight For Your Life, and again on each Second Wind', damage_types='-', base_xp=6.0),
    'x_restoration': XpSourcesRow(id='x_restoration', hook='h_heal', filter="player is healed (not shield restores, not the mod's own regen)", damage_types='-', base_xp=1.0),
    'x_enchanting': XpSourcesRow(id='x_enchanting', hook='h_add_inventory', filter='player picks up an elemental gun', damage_types='-', base_xp=2.0),
}
