"""Generate mod/skylands/sheet_data.py from the sheets: one frozen dataclass per sheet,
one instance per row. Run preflight first; this refuses to generate when it fails.

Usage: python tools/gen.py [--check]   (--check: fail if the generated file is stale)
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from preflight import load_sheets, preflight  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "mod" / "skylands" / "sheet_data.py"

# Columns that only track verification; they stay in the sheets, not the mod.
SKIP = {"in_game", "in_data", "parser_tested", "real_file_tested", "read_verified", "balanced_in_game"}


def class_name(sheet: str) -> str:
    return "".join(p.capitalize() for p in sheet.split("_")) + "Row"


def py_type(values: list[object]) -> str:
    kinds = {type(v) for v in values}
    if kinds <= {int}:
        return "int"
    if kinds <= {int, float}:
        return "float"
    if kinds <= {str}:
        return "str"
    return "float | str"


def render(sheets: dict[str, dict]) -> str:
    out = [
        '"""Generated by tools/gen.py from sheets/*.json. Do not edit; change the sheet."""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
    ]
    for name, sheet in sheets.items():
        cols = [c for c in sheet["columns"] if c not in SKIP]
        cls = class_name(name)
        out += ["", "@dataclass(frozen=True)", f"class {cls}:", f'    """{sheet["description"]}"""', ""]
        types = {c: py_type([r[c] for r in sheet["rows"]]) for c in cols}
        for c in cols:
            out.append(f"    {c}: {types[c]}")
        out += ["", "", f"{name.upper()}: dict[str, {cls}] = {{"]
        for row in sheet["rows"]:
            args = ", ".join(
                f"{c}={float(row[c])!r}" if types[c] == "float" or (types[c] == "float | str" and not isinstance(row[c], str)) else f"{c}={row[c]!r}" for c in cols
            )
            out.append(f"    {row['id']!r}: {cls}({args}),")
        out.append("}")
    return "\n".join(out) + "\n"


def main() -> int:
    sheets = load_sheets()
    errors, _ = preflight(sheets)
    if errors:
        print("preflight failed; run tools/preflight.py")
        return 1
    text = render(sheets)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("sheet_data.py is stale; run tools/gen.py")
            return 1
        print("sheet_data.py up to date")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
